# parameters for gd_standerled_ni

led_red: [255, 0, 0]
led_purple: [15, 0, 15]
led_blue: [0, 0, 15]
led_green: [0, 255, 0]
led_yellow: [17, 12, 0]
led_orange: [20, 5, 0]
led_white: [10, 10, 10]
led_off: [0, 0, 0]
