# parameters for gd_prediction2led
class3: [L,S,R]
class5: [TL,AL,S,AR,TR]
class6: [TL,AL,S,AR,TR,N_L]
class66: [YB_L,YB_S,YB_R,FT_L,FT_S,FT_R]
class7: [L_S,L_R,C_L,C_S,C_R,R_L,R_S]
class72: [L_S_S,L_R_S,C_L_S,C_S_S,C_R_S,R_L_S,R_S_S]
class8: [L_S_S,L_R_S,C_L_S,C_S_S,C_R_S,R_L_S,R_S_S,N_L]
class9: [L_L,L_S,L_R,C_L,C_S,C_R,R_L,R_S,R_R]

class3_pin: [0,6,12]
class5_pin: [2,4,6,8,10]
class6_pin: [2,4,6,8,10,14]
class7_pin: [0,2,4,6,8,10,12]
class8_pin: [0,2,4,6,8,10,12,14]
class9_pin: [0,2,4,6,8,10,12,14]

class3_pin_ws: [4,3,2]
class5_pin_ws: [1,2,3,4,5]
class6_pin_ws: [1,2,3,4,5,5]
class66_pin_ws: [2,1,0,6,5,4]
class7_pin_ws: [0,1,2,3,4,5,6]
class8_pin_ws: [0,1,2,3,4,5,6,6]
class9_pin_ws: [0,1,2,3,4,5,6,6,6]

led_high: 4095
led_mid: 2048
led_low: 512

thres_high: 0.6
thres_low: 0.3

